class OpenAI:
    API_TYPE = "azure"
    API_BASE = "https://eastus.api.cognitive.microsoft.com/"
    API_VERSION= "2023-03-15-preview"
    API_KEY = "51a522a1f13247918514f9c14b196625"
    MODEL = "Eximius-Resume"
    MODEL_JD = "eximius-davinci"
    MODEL_NAME = "exim-embedd" # "exim-embedding" #Vector Search

class Storage:

    AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=eximusstorage;AccountKey=RTWd7PylKJb5q9Wgf1TB+qiDJFVusaLcgDtciVzrQKu+EB76jjV8L5HckBmJ+EAA7MNY0AS0X4RI+ASt0yFWnw==;EndpointSuffix=core.windows.net"
    RAW_FILES_CONTAINER_NAME = "resume"
    CONVERTED_FILES_CONTAINER_NAME = "resume-parsed-files"


class Cosmos:
    URL = "https://eximiuscosmo.documents.azure.com:443/"
    KEY = "h6us8ihYGQd1xB5RDF0NQQJEMhgg3Z1q8U8VgYJgnahaADJ5oyb9OFCopGAYf5tRq0uYIp6RgSrrACDbDCpAZA=="
    DATABASE_NAME = 'eximiusCosmosDb'
    CONTAINER_NAME_RESUME = 'Resume'
    CONTAINER_NAME_JD = 'Job'

class JobRialto:
    API_KEY = '9368c1c6-221e-4d7d-8e94-ef1935edac3e'
    AUTH_TOKEN = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI0YTM1NjcxYi05ZTI1LTQxZGYtYTdiYy1jODY3Yjg3YmQ4Y2UiLCJpYXQiOiIwOC8xMC8yMDIzIDExOjAzOjIzIiwiVXNlcklkIjoiMGY1MDk4ZGItNjlmNy00NDcyLWI3YWYtMjhjOTE5MzhjNWFkIiwiVXNlck5hbWUiOiJNaW1hbnNoYSBHb3lhbCIsIkVtYWlsIjoibWltYW5zaGEuZ295YWxAY29tcHVubmVsZGlnaXRhbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJSZWNydWl0ZXIiLCJQZXJtaXNzaW9ucyI6IiIsIkFsbG93ZWRGZWF0dXJlc0lkcyI6IjUyY2MwNDE5LWM1M2QtNDk0Yi05YzA3LWZhZjFmYTNjMDc2MCw1NmY5YjExNC1mN2FhLTRhNjYtYmUxZC03MTQ5NGIyMTk1MDIsYzNhM2RlMzMtOGYzOC00ZjJlLWE5NzgtYWY2ZGRiODg3ODZmLDY3MGUzNjFmLTdlNzUtNDAzYy05ZGNkLTAxOTNmYTU2MTg5Yiw1Nzk2YjJmZC0wMjdiLTQwOTktOTE1MS1iZDExZTVmMGQ3ZjgsMzRmNDVhYTUtMjg1Yi00OTI4LTg5MTYtOTdmZTAzOGMzNGRhLGNlMDI5YjFiLWUxOTctNDRlNC05MDRkLWFiNmRmNTE0NTU2NCxmYzNkZjlmZi01YjNmLTQ1ZTktYjYzYy1lZDk0MWM3NzJmMTEsZTcxZGE3ZTUtNGY0NC00NDg2LThlMTMtODhkZTg4ZDM1YTAwLDgxNDU2Y2FjLTEwOWMtNDJiNi1iYzdjLWZkYWM3NGFkYzgxZixmOGQxNGY4Ny1jMjQ5LTQ1MjAtODQwNi1jMTcxODA1YzIzMzksODY1MjE0MDUtOGE4Zi00NTUxLWJkMWMtOWY5ODYxZTI4NWMwIiwiQWxsb3dlZE1vZHVsZXNJZHMiOiJlODlkM2Q1NS1jYmYwLTQ0MDAtYmM0NC04YjIzM2Q5YzA1NTIsYmMzOTdmNWUtMDEwYS00ZWFiLWIwNzUtZDQzMDYyODhkMjliLDZmZDg5MTRjLWJjODUtNDVlNS1iOTFjLTg2Y2I3YmQxNjA5MyxlNDI3YTM3Yy0xZDBmLTRjYzAtODJmMi1jZmU1YjEzYTA1MGIsNDY0NzZiYTItZGZhMC00NTRmLTg1NzMtYWQxMTNlYTRiMDJmLDU5Y2E3NTE1LWFjOTItNGE2Mi1iZWI3LTE4NTE5ZDUwMGEwZiw3OWIwNTFjZS03NDA4LTRmMWMtYTg2YS0xZWFjMzk2YjgyMjYsMjE0MDVkMWMtMGIzOC00MGRhLWExMDItNjc4MGMxZDliMzMyLDNkMGI3ODcxLTRiODgtNDBlZC1hNWJjLThkOGE2YmMyMzY3OCw4MTMzZjk2NC05MWYyLTRlNDctOGMwOS1mMDE2MDg4ZDdhYmEsYmU2ZGU0MDMtY2M5MC00MzI1LTkzNWQtZjk2NmY0M2MxMWY2LDkxZTNiNTVjLTkzZGMtNDkxOC05NmI2LTA2NTAyNTQyYzVlNyw0ZmMyODg1Ny1jNDI3LTRiMTctOGJlNS1lZGYxODdkYjQ5ZDcsZTI2MmE2ODktMmE1ZS00MDc5LWExYjMtNDJlZTdmM2FkZmFhLGZkNTRiYjYxLTY4NmUtNGQ3Yi1hMWEzLTY5MDViYWVmYTdlMyw3MmYyZjNkMy01NmY1LTQzZWItYmU5ZS00MmVmOTU4MzQ2MjUsMjUwNTM1NDQtODJkOC00YThjLWFmMmUtNmFiYzY2MWIzMzUzLDY3ODMzYzdlLWNjOWYtNDNhMi05YzU2LTZlZTJmNGMzYWQyZSxiN2U1YzBlYS1iYmU5LTRmY2QtOTViOS02MTBkNGNiNzcyNTQsMzc5MGRlZTMtMGIyYi00YWUzLWJiNzQtMzRjOTg2Y2Y5NWQxLDBkYjA3ODdmLTZhNzAtNDRiZS1iNmM2LTdhNTVkMjg4ODgwNCwwOTllZDllNS0zMzA3LTQxN2EtOGQ0Ny1kOWQ2MzBlNWUzNWMiLCIiOiIiLCJleHAiOjE2OTE2NjkwMDMsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZVJlY3VyaXRlciJ9.eq7x9dBktXedTm_8QlMtEHprE5PNQnmfZt0SDDlgU54'
    API_URL = 'https://qa.jobrialto.com/jobProvider-api/api/Jobs/'

class CogSearch:
    SEARCH_INDEX_NAME = "candidate-profile-100"
    SEARCH_INDEX_NAME_JOBSEARCH = "work-jd-vector-02" #"wv-jd-vector-02"
    SEARCH_ENDPOINT = "https://eximius-cogsarch.search.windows.net"
    SEARCH_API_KEY = "CpxhFEf7lguLcYa7CnXuRx5aQKjjPci0I57uv3i2riAzSeC4qSk1"
    availibility_range = 15 
    package_rate_range = 5
    years_of_experience_range = 5
    Search_radius = 100*1.609  # Search_radius in miles
    SEARCH_INDEX_NAME_VECTOR = "vector-candidate-profile-012"


class Weightage:
    parameter_weightage = {
        "Skills/Keywords": 0.1667,
        "Job Title": 0.1667,
        "Technology": 0.1667,
        "Tools": 0.1667,
        "Education": 0.1667,
        "Certification": 0.1667
    }


class Gmaps:
    API_KEY = "AIzaSyCC1M2XBigmfW-CFkAWCaYUSVmHl6a_-jc"


class ATS:
    ATS_NAME = "Jobrialto INC."
    SURVEY = "https://forms.office.com/r/v4j2n3Re0L"
    TIMEFRAME = "7 days"